# https://docs.openshift.com/container-platform/latest/rest_api/workloads_apis/cronjob-batch-v1.html
{{- range $cronjob := $.Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ $cronjob.id }}
spec:
  schedule: {{ $cronjob.schedule | quote }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ $cronjob.activeDeadlineSeconds }}
      template:
        spec:
          containers:
          - name: run-validation
            image: "{{ $.Values.image.repo }}:{{ $.Values.image.tag }}"
{{- if eq $cronjob.id "daily-validation" }}
            volumeMounts:
            - name: pagure-ssh-key
              mountPath: /secrets/pagure-ssh
              readOnly: true
            - name: pagure-keytab
              mountPath: /secrets/pagure-keytab
              readOnly: true
{{- end }}
            env:
{{- if eq $cronjob.id "daily-validation" }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-github
                  key: token
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-gitlab
                  key: token
            - name: PAGURE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-pagure-token
                  key: token
            - name: PAGURE_SSH_KEY
              value: /secrets/pagure-ssh/key
            - name: PAGURE_KEYTAB
              value: /secrets/pagure-keytab/keytab
{{- end }}
{{- if eq $cronjob.id "weekly-validation"}}
            - name: GITLAB_GNOME_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-gitlab-gnome
                  key: token
            - name: GITLAB_FREEDESKTOP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-gitlab-freedesktop
                  key: token
            - name: SALSA_DEBIAN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-salsa-debian
                  key: token
{{- end }}
            - name: SENTRY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-sentry
                  key: dsn
            - name: DEPLOYMENT
              value: {{ $.Values.deployment }}
            - name: GIT_AUTHOR_NAME
              value: "Packit Validation"
            - name: GIT_AUTHOR_EMAIL
              value: "validation@packit.dev"
            - name: GIT_COMMITTER_NAME
              value: "Packit Validation"
            - name: GIT_COMMITTER_EMAIL
              value: "validation@packit.dev"
            resources:
              {{- toYaml $.Values.resources | nindent 14 }}
{{- if eq $cronjob.id "daily-validation" }}
          volumes:
          - name: pagure-ssh-key
            secret:
              secretName: {{ $.Release.Name }}-pagure-ssh
              defaultMode: 0400
          - name: pagure-keytab
            secret:
              secretName: {{ $.Release.Name }}-pagure-keytab
              defaultMode: 0400
{{- end }}
          restartPolicy: OnFailure
---
{{- end }}
