name: Check templates

on:
  workflow_dispatch:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [packit-service-validation]

    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: make -C values/${{ matrix.chart }}/ template
